<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="22" height="32" viewBox="0 0 22 32">
<path fill="#fff" d="M0 0h6.7v32h-6.7v-32z"></path>
<path fill="#fff" d="M15.3 0h6.7v32h-6.7v-32z"></path>
</svg>
