<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="27" height="32" viewBox="0 0 27 32">
<path fill="#fff" d="M0 30.234v-28.415c-0.024-0.108-0.038-0.232-0.038-0.359 0-0.946 0.767-1.712 1.712-1.712 0.331 0 0.64 0.094 0.902 0.256l23.324 14.444c0.525 0.325 0.87 0.898 0.87 1.552s-0.345 1.227-0.862 1.547l-23.392 14.185c-0.245 0.15-0.541 0.239-0.858 0.239-0.916 0-1.659-0.743-1.659-1.659 0-0.028 0.001-0.055 0.002-0.082z"></path>
</svg>
